export const mockClinics = [
  {
    id: 1,
    name: "Clínica Vida & Saúde",
    description:
      "Cuidado completo com especialistas renomados e tecnologia de ponta.",
    image: "Clínica médica moderna com recepção elegante",
    category: "Clínica Geral",
    rating: 4.9,
    specialties: ["Cardiologia", "Dermatologia", "Pediatria"],
    address: "Av. Paulista, 1000 - São Paulo, SP",
    price: "150",
    featured: true,
  },
  {
    id: 2,
    name: "Centro Ortopédico Avançado",
    description: "Referência em ortopedia e reabilitação esportiva.",
    image: "Corredor de uma clínica de reabilitação com equipamentos",
    category: "Especializada",
    rating: 4.8,
    specialties: ["Ortopedia", "Fisioterapia"],
    address: "Rua Augusta, 500 - São Paulo, SP",
    price: "200",
    featured: false,
  },
  {
    id: 3,
    name: "Mente Sã Psicologia",
    description:
      "Ambiente acolhedor focado no seu bem-estar mental e emocional.",
    image: "Consultório de psicologia com poltronas confortáveis",
    category: "Bem-Estar",
    rating: 4.9,
    specialties: ["Psicologia", "Terapia de Casal"],
    address: "Rua das Flores, 200 - São Paulo, SP",
    price: "180",
    featured: true,
  },
  {
    id: 4,
    name: "Visão Clara Oftalmologia",
    description: "Tecnologia de ponta para a saúde dos seus olhos.",
    image: "Equipamento oftalmológico moderno em uma sala de exame",
    category: "Hospital",
    rating: 4.7,
    specialties: ["Oftalmologia", "Cirurgia Refrativa"],
    address: "Av. Brasil, 1500 - São Paulo, SP",
    price: "220",
    featured: false,
  },
  {
    id: 5,
    name: "Sorriso Perfeito Odontologia",
    description: "Cuidado odontológico completo para toda a família.",
    image: "Cadeira de dentista em um consultório moderno e bem iluminado",
    category: "Odontologia",
    rating: 4.8,
    specialties: ["Clareamento", "Implantes", "Ortodontia"],
    address: "Rua dos Pinheiros, 300 - São Paulo, SP",
    price: "130",
    featured: false,
  },
  {
    id: 6,
    name: "Derma Pelle Dermatologia",
    description:
      "Tratamentos estéticos e dermatológicos com tecnologia avançada.",
    image: "Sala de tratamento estético com lasers e equipamentos de pele",
    category: "Diagnósticos",
    rating: 4.9,
    specialties: ["Dermatologia Estética", "Laser"],
    address: "Av. Faria Lima, 800 - São Paulo, SP",
    price: "250",
    featured: true,
  },
  {
    id: 7,
    name: "VittaHub",
    description:
      "Plataforma completa de agendamento de consultas médicas com tecnologia inovadora.",
    image: "Interface moderna de agendamento online",
    category: "Tecnologia Médica",
    rating: 5.0,
    specialties: ["Agendamento Online", "Telemedicina", "Gestão de Clínicas"],
    address: "Russas - CE",
    price: "0",
    featured: true,
  },
  {
    id: 8,
    name: "Clínica Rio Saúde",
    description:
      "Cuidados médicos especializados no coração da cidade maravilhosa.",
    image: "Clínica moderna com vista para o mar",
    category: "Clínica Geral",
    rating: 4.8,
    specialties: ["Cardiologia", "Neurologia", "Endocrinologia"],
    address: "Copacabana - Rio de Janeiro, RJ",
    price: "180",
    featured: true,
  },
  {
    id: 9,
    name: "Centro Médico Belo Horizonte",
    description: "Excelência em atendimento médico na capital mineira.",
    image: "Centro médico com arquitetura moderna",
    category: "Hospital",
    rating: 4.7,
    specialties: ["Clínica Geral", "Pediatria", "Ginecologia"],
    address: "Savassi - Belo Horizonte, MG",
    price: "160",
    featured: false,
  },
  {
    id: 10,
    name: "Salvador Saúde Integral",
    description: "Cuidados médicos completos na capital baiana.",
    image: "Clínica com arquitetura colonial moderna",
    category: "Clínica Geral",
    rating: 4.6,
    specialties: ["Cardiologia", "Dermatologia", "Oftalmologia"],
    address: "Barra - Salvador, BA",
    price: "140",
    featured: false,
  },
  {
    id: 11,
    name: "Brasília Medical Center",
    description: "Tecnologia e humanização no centro do país.",
    image: "Centro médico com design futurista",
    category: "Hospital",
    rating: 4.9,
    specialties: ["Ortopedia", "Neurologia", "Cardiologia"],
    address: "Asa Sul - Brasília, DF",
    price: "200",
    featured: true,
  },
  {
    id: 12,
    name: "Porto Alegre Clínica",
    description: "Atendimento médico de qualidade no sul do país.",
    image: "Clínica com ambiente acolhedor",
    category: "Clínica Geral",
    rating: 4.5,
    specialties: ["Psicologia", "Dermatologia", "Endocrinologia"],
    address: "Moinhos de Vento - Porto Alegre, RS",
    price: "170",
    featured: false,
  },
];
