export const mockClinics = [
  {
    id: 1,
    name: "Clínica Vida & Saúde",
    description:
      "Cuidado completo com especialistas renomados e tecnologia de ponta.",
    image: "Clínica médica moderna com recepção elegante",
    category: "Clínica Geral",
    rating: 4.9,
    specialties: ["Cardiologia", "Dermatologia", "Pediatria"],
    address: "Av. Paulista, 1000 - São Paulo, SP",
    price: "150",
    featured: true,
  },
  {
    id: 2,
    name: "Centro Ortopédico Avançado",
    description: "Referência em ortopedia e reabilitação esportiva.",
    image: "Corredor de uma clínica de reabilitação com equipamentos",
    category: "Especializada",
    rating: 4.8,
    specialties: ["Ortopedia", "Fisioterapia"],
    address: "Rua Augusta, 500 - São Paulo, SP",
    price: "200",
    featured: false,
  },
  {
    id: 3,
    name: "Mente Sã Psicologia",
    description:
      "Ambiente acolhedor focado no seu bem-estar mental e emocional.",
    image: "Consultório de psicologia com poltronas confortáveis",
    category: "Bem-Estar",
    rating: 4.9,
    specialties: ["Psicologia", "Terapia de Casal"],
    address: "Rua das Flores, 200 - São Paulo, SP",
    price: "180",
    featured: true,
  },
  {
    id: 4,
    name: "Visão Clara Oftalmologia",
    description: "Tecnologia de ponta para a saúde dos seus olhos.",
    image: "Equipamento oftalmológico moderno em uma sala de exame",
    category: "Hospital",
    rating: 4.7,
    specialties: ["Oftalmologia", "Cirurgia Refrativa"],
    address: "Av. Brasil, 1500 - São Paulo, SP",
    price: "220",
    featured: false,
  },
  {
    id: 5,
    name: "Sorriso Perfeito Odontologia",
    description: "Cuidado odontológico completo para toda a família.",
    image: "Cadeira de dentista em um consultório moderno e bem iluminado",
    category: "Odontologia",
    rating: 4.8,
    specialties: ["Clareamento", "Implantes", "Ortodontia"],
    address: "Rua dos Pinheiros, 300 - São Paulo, SP",
    price: "130",
    featured: false,
  },
  {
    id: 6,
    name: "Derma Pelle Dermatologia",
    description:
      "Tratamentos estéticos e dermatológicos com tecnologia avançada.",
    image: "Sala de tratamento estético com lasers e equipamentos de pele",
    category: "Diagnósticos",
    rating: 4.9,
    specialties: ["Dermatologia Estética", "Laser"],
    address: "Av. Faria Lima, 800 - São Paulo, SP",
    price: "250",
    featured: true,
  },
  {
    id: 7,
    name: "VittaHub",
    description:
      "Plataforma completa de agendamento de consultas médicas com tecnologia inovadora.",
    image: "Interface moderna de agendamento online",
    category: "Tecnologia Médica",
    rating: 5.0,
    specialties: ["Agendamento Online", "Telemedicina", "Gestão de Clínicas"],
    address: "Russas - CE",
    price: "0",
    featured: true,
  },
];
